id: P004620
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:44:49.296549
source_metadata:
  id: bdr:W1PD159374
  title: བོད་ཀྱི་གསོ་བ་རིག་པའི་ལོ་རྒྱུས་གསོང་པོར་བརྗོད་པ་དྭངས་གཙང་ཆུ་བོའི་རྒྱུན་བཟང་།
  author: ''
  volumes:
    85ba9ca422ec4a3db0c955eef93ba862:
      image_group_id: I2PD17936
      title: ''
      volume_number: 1
      total_pages: 524
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
